:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 20
:queues:
  - ecs_service_provisioning
  - github_deploy
  - github_retrieve_branch
  - github_retrieve_branch_watch
  - slack_deploy_cluster
  - slack_deploy_target
  - slack_deploy_confirm
  - slack_deploy
  - slack_deploy_history
  - slack_command_receive
  - slack_interaction
  - workflow_deploy
